Repository Jadu07/CodeFlex, pull requests merged in 2024-10, with the labels that each got.

#13 Create Prime Checker
  Python/Prime Checker
Labels: hacktoberfest-accepted

#15 Create Even_Odd_Checker.py
  Python/Even_Odd_Checker.py
Labels: hacktoberfest-accepted, hacktoberfest

#18 Create Hello world.py
  Python/Hello world.py
Labels: hacktoberfest-accepted, hacktoberfest

#17 Create Sum_Of_Two_Prime.py
  Python/Sum_Of_Two_Prime.py
Labels: hacktoberfest-accepted, hacktoberfest

#21 Added code for reversing string provided to the function
  reverse_string.py
Labels: hacktoberfest-accepted, hacktoberfest

#22 Added the Optimized PrimeChecker Function
  Python/Prime Checker
  Python/PrimeChecker.py
Labels: hacktoberfest-accepted, hacktoberfest

#23 Added Tower of Hanoi code
  Python/tower_of_hanoi.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#26 Transpose-of-a-matrix python file
  Python/transpose_of_matrix.py
Labels: hacktoberfest-accepted, hacktoberfest

#27 Updated the temp.html file with valid HTML template
  HTML/temp.html
Labels: hacktoberfest-accepted, hacktoberfest

#28 Largest Number Finder in a list
  Python/LargestNumber.py
Labels: hacktoberfest-accepted, hacktoberfest

#29 Added multiple string input support, input cleaning (punctuation and spaces), detailed palindrome check feedback, character count, and palindrome check to string reversal functionality.
  reverse_string.py
  string_palindrome.py
Labels: hacktoberfest-accepted, hacktoberfest

#32 Add Increment Triangle Python Program
  Python/IncrementTriangle.py
Labels: hacktoberfest-accepted, hacktoberfest

#33 Create butterfly_pattern.py
  Python/butterfly_pattern.py
Labels: hacktoberfest-accepted, hacktoberfest

#37 Added linear search implementation
  Python/linear_search.py
Labels: hacktoberfest-accepted, hacktoberfest

#36 Added a file find_largest_number.py to find the largest number in a list
  Python/find_largest_number.py
Labels: hacktoberfest-accepted, hacktoberfest
